---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.11
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[t3-chef-client::default]
    attributes:
